version: '3.9'
services:

  demosso:
    image: 'postgres:14'
    container_name: demosso
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=demosso
      - POSTGRES_USER=demosso
      - POSTGRES_PASSWORD=password
